views.py
from flask import render_template, Blueprint, request, jsonify, url_for

from create_video import make_video

bp = Blueprint('video', __name__, url_prefix='/')


@bp.route('/', methods=['POST', 'GET'])
def get_args():
    title = 'Создать видео'
    return render_template('start_page.html', title=title)


@bp.route('/get_data', methods=['POST', 'GET'])
def get_data():
    path = request.form['inputPath']
    name = request.form['inputName']
    filename = request.form['inputFileName']
    result = make_video(path, name, filename)
    response = jsonify({'file_name': url_for('static', filename=result)})
    return response

templates/base.html
<!doctype html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="/static/style.css">
    <script
        src="https://code.jquery.com/jquery-3.7.1.js"
        integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4="
        crossorigin="anonymous">
    </script>
    <title>{{ title }}</title>

  </head>
  <body>
    <div class="container-fluid" id="back">
      {% block content %}
      {% endblock %}
    </div>
  </body>
</html>

templates/start_page.html
{% extends 'base.html' %}
{% block content %}
<div class="row" style="min-height: 100vh;">
    <div class="col-2" style="background: lightgrey;padding-top:15px;">
        <h1>menu</h1>
        <ul>
            <li>1 пункт</li>
            <li>2 пункт</li>
            <li>3 пункт</li>
            <li>4 пункт</li>
        </ul>
    </div>
    <div class="col-6" style="padding-top:15px;">
        <h1>Create video</h1>
        <form id="videoForm" method="post" action="" enctype="multipart/form-data">

            <div class="mb-3 row">
                <label for="inputPath" class="col-sm-2 col-form-label">Путь до директории</label>
                <div class="col-sm-10">
                    <input type="text" name="inputPath" class="form-control" id="inputPath">
                </div>
            </div>
            <div class="mb-3 row">
                <label for="inputName" class="col-sm-2 col-form-label">Имя секвенции</label>
                <div class="col-sm-10">
                    <input type="text" name="inputName" class="form-control" id="inputName" placeholder="Название без номера и формата, например 'blood'">
                </div>
            </div>
            <div class="mb-3 row">
                <label for="inputFileName" class="col-sm-2 col-form-label">Название видео</label>
                <div class="col-sm-10">
                    <input type="text" name="inputFileName" class="form-control" id="inputFileName" placeholder="Название и формат, например 'blood.mov'">
                </div>
            </div>
            <button type="submit" class="btn btn-secondary">Создать</button>
        </form>
    </div>
    <div id="video" class="col" style="background: lightgrey;padding-top:15px;">
        <h1>Result</h1>
    </div>
</div>

<script defer>
    $(document).on('submit', "#videoForm", function (e) {
        e.preventDefault();
        var data = $('#videoForm').serializeArray();
        var token = '{{ csrf_token }}';
        var formData = new FormData($(this)[0]);
        formData.append('path', data.find(x => x.name === 'inputPath').value);
        formData.append('name', data.find(x => x.name === 'inputName').value);
        formData.append('filename', data.find(x => x.name === 'inputFileName').value);
        $.ajax({
                type: "POST",
                url: "{{url_for('video.get_data')}}",
                headers: {'X-CSRFToken': token},
                data: $('#videoForm').serialize(),
                success: function(response) {
                console.log(response);
                $('#video').append(
                                    '<video width="400" height="300" controls>' +
                                        '<source src="' + response.file_name + '" type="video/mp4">' +
                                    '</video>'
                                    )
                },
                error: function() {
                    console.log('it broke');
                },
            });
        });
</script>
{% endblock %}